visual_odom:
  ros__parameters:
    # Depth filtering parameters
    min_depth: 400        # Minimum depth in mm
    max_depth: 5000       # Maximum depth in mm

    # RANSAC parameters
    ransac:
      evaluation_tolerance: 50    # Tolerance for inlier evaluation in mm
      iterations: 1000             # Number of RANSAC iterations
      sample_size: 3              # Minimum number of samples for robust estimation
    
    # Temporal parameters
    waiting_frames: 3             # Number of frames to wait before processing

    # Camera intrinsic parameters
    camera:
      focal_length: 526.61        # Focal length in pixels
      principal_point_u: 318.525  # Principal point u coordinate
      principal_point_v: 241.181  # Principal point v coordinate

    # Rosbag configuration
    #rosbag_path: "/media/sf_VM_Exchange/Rosbags/trans_rot_2_bag/rosbag2_2026_03_24-10_48_57_0.mcap"
    rosbag_path: "/media/sf_VM_Exchange/Rosbags/pure_rotation_2_bag/rosbag2_2026_03_24-10_48_19_0.mcap"
    